/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PersistencePolicies struct {
	BookkeeperEnsemble             int32   `json:"bookkeeperEnsemble,omitempty"`
	BookkeeperWriteQuorum          int32   `json:"bookkeeperWriteQuorum,omitempty"`
	BookkeeperAckQuorum            int32   `json:"bookkeeperAckQuorum,omitempty"`
	ManagedLedgerMaxMarkDeleteRate float64 `json:"managedLedgerMaxMarkDeleteRate,omitempty"`
}
