/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type BacklogQuota struct {
	Limit  int64  `json:"limit,omitempty"`
	Policy string `json:"policy,omitempty"`
}
