/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type ResourceUsage struct {
	Usage float64 `json:"usage,omitempty"`
	Limit float64 `json:"limit,omitempty"`
}
