/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type PublishRate struct {
	PublishThrottlingRateInMsg  int32 `json:"publishThrottlingRateInMsg,omitempty"`
	PublishThrottlingRateInByte int64 `json:"publishThrottlingRateInByte,omitempty"`
}
