/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type SystemResourceUsage struct {
	BandwidthIn  *ResourceUsage `json:"bandwidthIn,omitempty"`
	BandwidthOut *ResourceUsage `json:"bandwidthOut,omitempty"`
	Cpu          *ResourceUsage `json:"cpu,omitempty"`
	Memory       *ResourceUsage `json:"memory,omitempty"`
	DirectMemory *ResourceUsage `json:"directMemory,omitempty"`
}
