/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AuthPolicies struct {
	NamespaceAuth         map[string][]string            `json:"namespace_auth,omitempty"`
	DestinationAuth       map[string]map[string][]string `json:"destination_auth,omitempty"`
	SubscriptionAuthRoles map[string][]string            `json:"subscription_auth_roles,omitempty"`
}
