/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DelayedDeliveryPolicies struct {
	TickTime int64 `json:"tickTime,omitempty"`
	Active   bool  `json:"active,omitempty"`
}
