/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MessageIdImpl struct {
	LedgerId       int64 `json:"ledgerId,omitempty"`
	EntryId        int64 `json:"entryId,omitempty"`
	PartitionIndex int32 `json:"partitionIndex,omitempty"`
}
