/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type CursorDetails struct {
	CursorBacklog  int64 `json:"cursorBacklog,omitempty"`
	CursorLedgerId int64 `json:"cursorLedgerId,omitempty"`
}
