/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OffloadProcessStatus struct {
	Status                  string         `json:"status,omitempty"`
	LastError               string         `json:"lastError,omitempty"`
	FirstUnoffloadedMessage *MessageIdImpl `json:"firstUnoffloadedMessage,omitempty"`
}
