/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type LongRunningProcessStatus struct {
	Status    string `json:"status,omitempty"`
	LastError string `json:"lastError,omitempty"`
}
