/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AutoTopicCreationOverride struct {
	AllowAutoTopicCreation bool   `json:"allowAutoTopicCreation,omitempty"`
	TopicType              string `json:"topicType,omitempty"`
	DefaultNumPartitions   int32  `json:"defaultNumPartitions,omitempty"`
}
