/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type ConsumerStats struct {
	MsgRateOut                   float64           `json:"msgRateOut,omitempty"`
	MsgThroughputOut             float64           `json:"msgThroughputOut,omitempty"`
	BytesOutCounter              int64             `json:"bytesOutCounter,omitempty"`
	MsgOutCounter                int64             `json:"msgOutCounter,omitempty"`
	MsgRateRedeliver             float64           `json:"msgRateRedeliver,omitempty"`
	ConsumerName                 string            `json:"consumerName,omitempty"`
	AvailablePermits             int32             `json:"availablePermits,omitempty"`
	UnackedMessages              int32             `json:"unackedMessages,omitempty"`
	BlockedConsumerOnUnackedMsgs bool              `json:"blockedConsumerOnUnackedMsgs,omitempty"`
	LastAckedTimestamp           int64             `json:"lastAckedTimestamp,omitempty"`
	LastConsumedTimestamp        int64             `json:"lastConsumedTimestamp,omitempty"`
	Metadata                     map[string]string `json:"metadata,omitempty"`
	Address                      string            `json:"address,omitempty"`
	ConnectedSince               string            `json:"connectedSince,omitempty"`
	ClientVersion                string            `json:"clientVersion,omitempty"`
}
