/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type NonPersistentSubscriptionStats struct {
	MsgRateOut                       float64         `json:"msgRateOut,omitempty"`
	MsgThroughputOut                 float64         `json:"msgThroughputOut,omitempty"`
	BytesOutCounter                  int64           `json:"bytesOutCounter,omitempty"`
	MsgOutCounter                    int64           `json:"msgOutCounter,omitempty"`
	MsgRateRedeliver                 float64         `json:"msgRateRedeliver,omitempty"`
	MsgBacklog                       int64           `json:"msgBacklog,omitempty"`
	MsgBacklogNoDelayed              int64           `json:"msgBacklogNoDelayed,omitempty"`
	BlockedSubscriptionOnUnackedMsgs bool            `json:"blockedSubscriptionOnUnackedMsgs,omitempty"`
	MsgDelayed                       int64           `json:"msgDelayed,omitempty"`
	UnackedMessages                  int64           `json:"unackedMessages,omitempty"`
	Type_                            string          `json:"type,omitempty"`
	ActiveConsumerName               string          `json:"activeConsumerName,omitempty"`
	MsgRateExpired                   float64         `json:"msgRateExpired,omitempty"`
	LastExpireTimestamp              int64           `json:"lastExpireTimestamp,omitempty"`
	LastConsumedFlowTimestamp        int64           `json:"lastConsumedFlowTimestamp,omitempty"`
	LastConsumedTimestamp            int64           `json:"lastConsumedTimestamp,omitempty"`
	LastAckedTimestamp               int64           `json:"lastAckedTimestamp,omitempty"`
	Consumers                        []ConsumerStats `json:"consumers,omitempty"`
	IsReplicated                     bool            `json:"isReplicated,omitempty"`
	MsgDropRate                      float64         `json:"msgDropRate,omitempty"`
}
