/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BookieInfo struct {
	Rack     string `json:"rack,omitempty"`
	Hostname string `json:"hostname,omitempty"`
}
