/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type OffloadPolicies struct {
	OffloadersDirectory                          string `json:"offloadersDirectory,omitempty"`
	ManagedLedgerOffloadDriver                   string `json:"managedLedgerOffloadDriver,omitempty"`
	ManagedLedgerOffloadMaxThreads               int32  `json:"managedLedgerOffloadMaxThreads,omitempty"`
	ManagedLedgerOffloadPrefetchRounds           int32  `json:"managedLedgerOffloadPrefetchRounds,omitempty"`
	ManagedLedgerOffloadThresholdInBytes         int64  `json:"managedLedgerOffloadThresholdInBytes,omitempty"`
	ManagedLedgerOffloadDeletionLagInMillis      int64  `json:"managedLedgerOffloadDeletionLagInMillis,omitempty"`
	S3ManagedLedgerOffloadRegion                 string `json:"s3ManagedLedgerOffloadRegion,omitempty"`
	S3ManagedLedgerOffloadBucket                 string `json:"s3ManagedLedgerOffloadBucket,omitempty"`
	S3ManagedLedgerOffloadServiceEndpoint        string `json:"s3ManagedLedgerOffloadServiceEndpoint,omitempty"`
	S3ManagedLedgerOffloadMaxBlockSizeInBytes    int32  `json:"s3ManagedLedgerOffloadMaxBlockSizeInBytes,omitempty"`
	S3ManagedLedgerOffloadReadBufferSizeInBytes  int32  `json:"s3ManagedLedgerOffloadReadBufferSizeInBytes,omitempty"`
	S3ManagedLedgerOffloadRole                   string `json:"s3ManagedLedgerOffloadRole,omitempty"`
	S3ManagedLedgerOffloadRoleSessionName        string `json:"s3ManagedLedgerOffloadRoleSessionName,omitempty"`
	GcsManagedLedgerOffloadRegion                string `json:"gcsManagedLedgerOffloadRegion,omitempty"`
	GcsManagedLedgerOffloadBucket                string `json:"gcsManagedLedgerOffloadBucket,omitempty"`
	GcsManagedLedgerOffloadMaxBlockSizeInBytes   int32  `json:"gcsManagedLedgerOffloadMaxBlockSizeInBytes,omitempty"`
	GcsManagedLedgerOffloadReadBufferSizeInBytes int32  `json:"gcsManagedLedgerOffloadReadBufferSizeInBytes,omitempty"`
	GcsManagedLedgerOffloadServiceAccountKeyFile string `json:"gcsManagedLedgerOffloadServiceAccountKeyFile,omitempty"`
	FileSystemProfilePath                        string `json:"fileSystemProfilePath,omitempty"`
	FileSystemURI                                string `json:"fileSystemURI,omitempty"`
	S3Driver                                     bool   `json:"s3Driver,omitempty"`
	GcsDriver                                    bool   `json:"gcsDriver,omitempty"`
	FileSystemDriver                             bool   `json:"fileSystemDriver,omitempty"`
}
